### PR TITLE
Unify -x<language> option usage

### LINKED ISSUE #208: C++: hawkmoth warns about `#pragma once in main file`
hawkmoth (or more likely, clang) warns about `#pragma once in main file`.

To reproduce, try to add documentation for this file:
```cpp
#pragma once

/*
 * Test doc
 */
void test_function() {}
```

The warning has no impact on the output.

### PR DESCRIPTION
**Pull request by jnikula**
Move the clang language selection at a lower level, do it unconditionally, and add -header too. This unifies -x option across the extension, tests ,and cli.

Fixes #208

### CODE REVIEW

**Comment by BrunoMSantos** [comment]
Looks great!

**Comment by jnikula** [comment]
> Looks great!

Thanks; I additionally pushed some tests that would fail without the fixes in the series. Would you mind eyeballing them too, please?

File: test/c/pragma-once.h [hunk 1]
```diff
@@ -0,0 +1,2 @@
+/** Ensure this file is parsed as a header */
+#pragma once
```
Comment (BrunoMSantos) [inline test/c/pragma-once.h:2]: Honestly, the whole error this would generate otherwise is a bit bogus if all it takes is to have `-xc*` or `-xc*-header`. Not sure we can rely on these tests failing long term is what I'm saying, so I'm not sure the tests are useful at all.

Not to mention it's a non standard pragma...

I understand why you're adding them and I won't oppose, but if it were only up to me, I wouldn't include these.

Comment (jnikula) [reply test/c/pragma-once.h]: Fair points. I was hoping to add some tests for the fixes, but this is probably a bit fragile indeed. Threw them away.
